### ISSUE TITLE
This isn't an issue but a recommendation for music!

### ISSUE THREAD

**Issue by Shadeys** [Amenofisch/ELK-BLEDOM#5]
You should add an ability to play music from Spotify, youtube music, iTunes etc.

And for the lights to change to a different color when the bass starts. And for the lights to change the brightness from 20% to 100% depending on the volume of the voice or voices in the song.

**Comment by Amenofisch** [comment]
Hey, first of all. I never thought someone is gonna ever look at this, so im kinda surprised. 
Well, this controller has already a built-in function react to sound using it's microphone but it's kinda trash lol.
It's worth to mention that with this current setup it's not possible to keep up with the speed of the music since this node app always makes a new connection to the LED Controller after executing it's command. 

I would have to adjust the script to make it faster, but it's currently not in my interest.

Thanks for your cool idea anyway. Maybe if im bored sometime i'll take a look if i can make it work.

**Comment by Shadeys** [comment]
Well I'm a programmer, and i can find anything fast on github so i wanted to try to edit the current code and make my own app that is faster, you can play music from music apps, the microphone function to be very different, the app to support RGBIC strips.

**Comment by Shadeys** [comment]
hey, so can you test this? I don't know how you make it into an apk https://github.com/Shadeys/DuoCo

**Comment by Shadeys** [comment]
@Amenofisch Not sure if it will work, but if some parts of it work you can edit it so that it works perfectly in your app.

**Comment by Amenofisch** [comment]
Hey @Shadeys, I'm starting to test it now. The code looks good, no idea if it works _yet_. One thing that I've noticed so far, that `Spotify.js` doesn't belong into the `Config` folder. I recommend making a new folder for it.

**Comment by Amenofisch** [comment]
Sooo, i looked over it. It looks like it should work, although i have found out, that you copy and pasted the constructor and some other code into `./modules/ledstrip.js`, since that file isn't a class/module you can't have a constructor. 
Please adjust it accordingly. Otherwise I really like your Idea. :) 

Also you may want to remove your Client Secret for Spotify from the code unless you've resetted it. Also moving the Client Secret and ExpireDate into the config.json would be good practice.

Also what is that `Duoc` in the constructor of `ledstrip.js`? That doesn't exist anywhere

**Comment by Shadeys** [comment]
I never said im done with it, i just said that i am still working on it. But that im still figuring out the code you made, i did copy paste a little bit of code in ./modules/ledstrip.js.

**Comment by Shadeys** [comment]
I stopped coding a year ago and im trying to restart it!

**Comment by Amenofisch** [comment]
> I never said im done with it, i just said that i am still working on it. But that im still figuring out the code you made, i did copy paste a little bit of code in ./modules/ledstrip.js.

Well you said that i should test it lol. Anyway, feel free to ping me if you feel ready or need any help. You can also contact me on discord: Amenofisch#5368

**Comment by Shadeys** [comment]
Btw i was searching through github and landed here https://github.com/SuperVK/Huetify

**Comment by Shadeys** [comment]
Think you can use it a little bit

**Comment by Shadeys** [comment]
> > I never said im done with it, i just said that i am still working on it. But that im still figuring out the code you made, i did copy paste a little bit of code in ./modules/ledstrip.js.
> 
> Well you said that i should test it lol. Anyway, feel free to ping me if you feel ready or need any help. You can also contact me on discord: Amenofisch#5368

my discord is DShadeyy#8180

**Comment by Shadeys** [comment]
When do you think you could add me on discord?

**Comment by Shadeys** [comment]
Well tried to fix some things https://github.com/Shadeys/DuoCo

**Comment by Shadeys** [comment]
btw what did you use to test my code?

**Comment by Amenofisch** [comment]
I just looked at it using VS Code and took a look over all code, and saw the errors. Btw there are still some there...

**Comment by Shadeys** [comment]
oh thank you for telling me what you are using, and i figured you are going to find the same errors i still can't figure out how to make it a module haha

**Comment by Shadeys** [comment]
will you add me on discord? my discord is DShadeyy#8180

**Comment by Shadeys** [comment]
btw fixed some things up on my code can you try it out? https://github.com/Shadeys/DuoCo/blob/production/modules/duoc.js

**Comment by Amenofisch** [comment]
Hey, could you please open up a pull request so that i can comment the stuff that has to be corrected?

**Comment by Shadeys** [comment]
Hey by the way, i fixed the many issues i found! Run the code now!

**Comment by Shadeys** [comment]
Wirst du mich auf Discord hinzufügen?

**Comment by Shadeys** [comment]
Mein Discord ist DShadeyy#8180
